# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.44.0"
"rocks-git.nvim" = "2.5.3"
nvim-lspconfig = "2.1.0"
"marks.nvim" = "scm"
nvim-autopairs = "scm"
"indent-blankline.nvim" = "3.9.0"
nvim-cmp = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
cmp-buffer = "scm"
cmp-nvim-lsp = "scm"
"lualine.nvim" = "scm"
"gitsigns.nvim" = "1.0.2"
nvim-dap = "0.10.0"
nvim-dap-python = "scm"
neogit = "2.0.0"

[plugins.cmp-nvim-lsp-signature-help]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
rev = "031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.10.0"

[plugins.vim-moonfly-colors]
git = "bluz71/vim-moonfly-colors"
rev = "ff822100c5d268e0db79e8e725cbd3ade3470de3"
