# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.47.4"
"rocks-git.nvim" = "2.5.10"
nvim-lspconfig = "2.7.0"
"marks.nvim" = "scm"
nvim-autopairs = "scm"
"indent-blankline.nvim" = "3.9.1"
nvim-cmp = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
cmp-buffer = "scm"
cmp-nvim-lsp = "scm"
"lualine.nvim" = "scm"
"gitsigns.nvim" = "2.1.0"
nvim-dap = "0.10.0"
nvim-dap-python = "scm"
neogit = "3.0.0"
"mason.nvim" = "2.2.1"

[plugins.cmp-nvim-lsp-signature-help]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
rev = "fd3e882e56956675c620898bf1ffcf4fcbe7ec84"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.10.0"

[plugins."cyberdream.nvim"]
git = "scottmckendry/cyberdream.nvim"
rev = "v5.3.0"
